/**
 * Sample Gig Data
 */
import { Gig } from './types';

export const SAMPLE_GIGS: Gig[] = [
    {
        id: '1',
        title: 'Design a Event Poster for College Fest',
        budget: 1500,
        postedBy: 'Aria S.',
        college: 'NIFT DELHI',
        collegeCode: 'nift',
        category: 'design',
        timeAgo: '2h ago',
        applicants: 5,
        posterDetails: {
            bio: 'Final year Fashion Comms student. Obsessed with experimental typography. Need someone who acts fast and gets the event aesthetic fr.',
            expertise: ['Poster Design', 'Typography', 'Adobe Suite'],
            pastGigs: 12,
            rating: 4.8,
            reviewCount: 24,
            responseTime: 'Within 2 hours',
            verified: true,
            memberSince: 'Aug 2024',
            completionRate: 96,
        },
    },
    {
        id: '2',
        title: 'Write Copy for Startup Landing Page',
        budget: 2000,
        postedBy: 'Rohan K.',
        college: 'DU NORTH',
        collegeCode: 'du',
        category: 'writing',
        timeAgo: '4h ago',
        applicants: 3,
        posterDetails: {
            bio: 'Running a small digital agency on the side. Need crisp copy for my new client\'s landing page. No ChatGPT stuff pls, need human creativity.',
            expertise: ['Copywriting', 'SEO', 'Web Content'],
            pastGigs: 8,
            rating: 4.6,
            reviewCount: 15,
            responseTime: 'Within 1 hour',
            verified: true,
            memberSince: 'Oct 2024',
            completionRate: 100,
        },
    },
    {
        id: '3',
        title: 'Build a React Native Component',
        budget: 3500,
        postedBy: 'Priya M.',
        college: 'IIT BOMBAY',
        collegeCode: 'iit',
        category: 'tech',
        timeAgo: '6h ago',
        applicants: 8,
        posterDetails: {
            bio: 'CS undergrad building a gym tracking app. Stuck on some complex reanimated gestures. Need a hand optimizing the code.',
            expertise: ['React Native', 'Typescript', 'Animation'],
            pastGigs: 15,
            rating: 4.9,
            reviewCount: 32,
            responseTime: 'Within 30 mins',
            verified: true,
            memberSince: 'Jun 2024',
            completionRate: 98,
        },
    },
    {
        id: '4',
        title: 'Instagram Growth Strategy for New Brand',
        budget: 1800,
        postedBy: 'Vikram D.',
        college: 'BITS PILANI',
        collegeCode: 'bits',
        category: 'marketing',
        timeAgo: '1d ago',
        applicants: 12,
        posterDetails: {
            bio: 'Launched a thrift store on IG last month. Need help growing followers organically. Budget is tight but payout is instant.',
            expertise: ['Instagram Growth', 'Reels', 'Community Mgmt'],
            pastGigs: 6,
            rating: 4.5,
            reviewCount: 11,
            responseTime: 'Within 3 hours',
            verified: false,
            memberSince: 'Dec 2024',
            completionRate: 92,
        },
    },
    {
        id: '5',
        title: 'Edit Promotional Video for College Club',
        budget: 2500,
        postedBy: 'Sneha R.',
        college: 'JNU DELHI',
        collegeCode: 'du',
        category: 'design',
        timeAgo: '3h ago',
        applicants: 7,
        posterDetails: {
            bio: 'Cultural Secy here. We need a sick aftermovie for the freshers party. Raw footage is ready, just need magic edits defined.',
            expertise: ['Premiere Pro', 'Color Grading', 'After Effects'],
            pastGigs: 4,
            rating: 4.7,
            reviewCount: 8,
            responseTime: 'Within 1 hour',
            verified: true,
            memberSince: 'Sep 2024',
            completionRate: 100,
        },
    },
    {
        id: '6',
        title: 'Manage Social Media for College Fest Week',
        budget: 3000,
        postedBy: 'Aditya P.',
        college: 'SRCC DELHI',
        collegeCode: 'du',
        category: 'marketing',
        timeAgo: '5h ago',
        applicants: 15,
        posterDetails: {
            bio: 'Handling PR for Crossroads. It\'s gonna be hectic. Need someone to live-tweet and manage stories during the celeb night.',
            expertise: ['Live Coverage', 'Twitter/X', 'Crisis Mgmt'],
            pastGigs: 9,
            rating: 4.8,
            reviewCount: 18,
            responseTime: 'Within 45 mins',
            verified: true,
            memberSince: 'Jul 2024',
            completionRate: 94,
        },
    },
    {
        id: '7',
        title: 'UI/UX Design for Campus Delivery App',
        budget: 4000,
        postedBy: 'Kavya N.',
        college: 'NID AHMEDABAD',
        collegeCode: 'nift',
        category: 'design',
        timeAgo: '8h ago',
        applicants: 10,
        posterDetails: {
            bio: 'Working on my graduation project about food delivery. Need a UI buddy to help speed up the Figma prototyping. High fidelity only.',
            expertise: ['Figma', 'Prototyping', 'Design Systems'],
            pastGigs: 20,
            rating: 5.0,
            reviewCount: 42,
            responseTime: 'Within 15 mins',
            verified: true,
            memberSince: 'Mar 2024',
            completionRate: 100,
        },
    },
];

